[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "vocaludf"
version = "0.1"

[tool.setuptools.packages]
find = {}  # Scan the project directory with the default parameters