db_dir: /gscratch/balazinska/enhaoz/VOCAL-UDF/duckdb_dir
data_dir: /gscratch/balazinska/enhaoz/VOCAL-UDF/data
output_dir: /gscratch/balazinska/enhaoz/VOCAL-UDF/outputs
prompt_dir: /gscratch/balazinska/enhaoz/VOCAL-UDF/prompts
log_dir: /gscratch/balazinska/enhaoz/VOCAL-UDF/logs
model_dir: /gscratch/balazinska/enhaoz/VOCAL-UDF/data/models
llava_path: /gscratch/balazinska/enhaoz/VOCAL-UDF/data/models/llava-1.5-7b-hf
query_parser:
  temperature: 0.2
  top_p: 0.5
udf_proposer:
  temperature: 0.2
  top_p: 0.5
interpretation_generator:
  temperature: 0.7
  top_p: 1
  max_tokens: 4095
udf_generator:
  temperature: 0.2
  top_p: 0.5
  n_train: 10000
  n_test: 10000
clevrer:
  height: 320
  width: 480
  dataset_size: 10000
  features_dir: /gscratch/balazinska/enhaoz/VOCAL-UDF/duckdb_dir/features/clevrer_three_clips
  video_frames_dir: /gscratch/balazinska/enhaoz/VOCAL-UDF/data/clevrer/video_frames
  input_query_file: /gscratch/balazinska/enhaoz/VOCAL-UDF/data/clevrer/3_new_udfs_labels.json
  onames:
    - object
clevr:
  height: 320
  width: 480
  dataset_size: 15000
  input_query_file: /gscratch/balazinska/enhaoz/VOCAL-UDF/data/clevr/3_new_udfs_labels.json
  onames:
    - object
charades:
  dataset_size: 9601
  features_dir: /gscratch/balazinska/enhaoz/VOCAL-UDF/duckdb_dir/features/charades_three_clips
  video_frames_dir: /gscratch/balazinska/enhaoz/VOCAL-UDF/data/charades/frames
  # input_query_file: /gscratch/balazinska/enhaoz/VOCAL-UDF/data/charades/3_new_udfs_labels-npred=5-nobj_pred=1.json
  # input_query_file: /gscratch/balazinska/enhaoz/VOCAL-UDF/data/charades/single_semantic-unavailable=1-npred=3-nobj_pred=2-nvars=2-depth=1.json
  input_query_file: /gscratch/balazinska/enhaoz/VOCAL-UDF/data/charades/unavailable=2-npred=4-nobj_pred=1-nvars=3-depth=2.json
  onames:
    - person
    - bag
    - bed
    - blanket
    - book
    - box
    - broom
    - chair
    - closet/cabinet
    - clothes
    - cup/glass/bottle
    - dish
    - door
    - doorknob
    - doorway
    - floor
    - food
    - groceries
    - laptop
    - light
    - medicine
    - mirror
    - paper/notebook
    - phone/camera
    - picture
    - pillow
    - refrigerator
    - sandwich
    - shelf
    - shoe
    - sofa/couch
    - table
    - television
    - towel
    - vacuum
    - window
visprog:
  program_generator:
    temperature: 0.2
    top_p: 0.5
  thumbnail_dir: /Users/zhangenhao/Desktop/vocalexplore-demo/ui_db_dir_224/thumbnails
  feature_names:
    - r3d_18_ap_mean_stride32_flatten
  ignore_labels:
    - neutral
    - lie down
    - stand up
  eager_feature_extraction_unlabeled: true
  eager_feature_extraction_unlabeled_batch_size: 500
  eager_feature_extraction_labeled: true
  eager_model_training: true
  cpus: 4
  gpus: 0
  suspend_lowp: true
  min_labels: 15
  mm_device: cpu
  serial_kfold: true
  explorer: randomifuniform
  al_vids_x: 10
  bandit_kfold_k: 3
  bandit_eval_metric: ml_f1_score_macro
  # Fraction of labeled data to hold out when tuning the F1 threshold.
  fraction_f1_val: 0.2
  bandit_type: exp
  bandit_C: 5
  bandit_T: 50
  bandit_window: 5
  async_bandit: true